version: '3.8'

services:
  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - '6379:6379'
    command: ["redis-server", "--appendonly", "yes"]

  backend:
    build: .
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - redis